# Problem Statement 1:

## Solution

1. Correct since 25 is inclusive in the null hypothesis and all remaining numbers are included in the alternate hypothesis.

2. Incorrect since greater than 10 is included in null hypothesis and 10 is included in the alternate hypothesis but less than 10 is not included. 

3. Correct since 50 is inclusive in the null hypothesis and all remaining numbers are included in the alternate hypothesis.

4. Incorrect since p = 0.1 is included in null hypothesis and p = 0.5 is included in the alternate hypothesis but remaining numbers (x<0.1, 0.1<x<0.5, x>0.5) are not included.

5. Incorrect since 30 is included in null hypothesis and greater than 30 is included in the alternate hypothesis but less than 30 is not included. 

# Problem Statement 2:

## Solution

In [1]:
%reset -f

import numpy as np
from scipy import stats

h0 = 'Mean Value of Books <= 52'
h1 = 'Mean Value of Books > 52'

print('-' * 50)

print('Null Hypothesis : ', h0)
print('Alternate Hypothesis : ', h1)

#Population Data
pop_mean = 52
std = 4.50


# Sample Data
n = 100
sample_mean = 52.80
alpha = 0.05

print('-' * 50)
# Z-Test

z_test = (sample_mean - pop_mean) / (std / (n ** 0.5))
print('Z test Value : {:.2f}'.format(z_test))


# Z(0.05)

z = np.abs(stats.norm.ppf(alpha))
print('Z value at 5% Significance : {:.2f}'.format(z))

print('-' * 50)
print('We can see 1.78 > 1.64, and since it is right tail test, the \
null hypothesis (h0) is rejected.')

print('Conclusion : The book prices are high in college bookstore.')
print('-' * 50)




--------------------------------------------------
Null Hypothesis :  Mean Value of Books <= 52
Alternate Hypothesis :  Mean Value of Books > 52
--------------------------------------------------
Z test Value : 1.78
Z value at 5% Significance : 1.64
--------------------------------------------------
We can see 1.78 > 1.64, and since it is right tail test, the null hypothesis (h0) is rejected.
Conclusion : The book prices are high in college bookstore.
--------------------------------------------------


# Problem Statement 3:

## Solution

In [2]:
%reset -f

import numpy as np
from scipy import stats

h0 = 'Avg pollutant quantity < 34 ppm'
h1 = 'Avg pollutant quantity >= 34 ppm'

print('-' * 50)

print('Null Hypothesis : ', h0)
print('Alternate Hypothesis : ', h1)

pop_mean = 34
pop_std = 8

alpha = 0.01

n = 50
sample_mean = 32.5

print('-' * 50)

z_test = (sample_mean - pop_mean) / (pop_std / (n ** 0.5))
print('Z test Value : {:.2f}'.format(z_test))

z = np.abs(stats.norm.ppf(alpha))
print('Z value at 1% Significance : {:.2f}'.format(z))

print('-' * 50)

print('Since -1.33 < 2.33 and this is a right tailed test. We cannot reject the null hypothesis.')
print('Conclusion : The claim made by the factory representatives is correct.')
print('-' * 50)

--------------------------------------------------
Null Hypothesis :  Avg pollutant quantity < 34 ppm
Alternate Hypothesis :  Avg pollutant quantity >= 34 ppm
--------------------------------------------------
Z test Value : -1.33
Z value at 1% Significance : 2.33
--------------------------------------------------
Since -1.33 < 2.33 and this is a right tailed test. We cannot reject the null hypothesis.
Conclusion : The claim made by the factory representatives is correct.
--------------------------------------------------


# Problem Statement 4:

## Solution

In [3]:
%reset -f

import numpy as np
from scipy import stats

h0 = 'Avg Family spends on Dental = 1135'
h1 = 'Avg Family spends on Dental != 1135'

print('-' * 50)

print('Null Hypothesis : ', h0)
print('Alternate Hypothesis : ', h1)

pop_mean = 1135

alpha = 0.05

n = 22
df = n - 1
sample_mean = 1031.31
sample_std = 234.85

print('-' * 50)

t_test = (sample_mean - pop_mean) / (sample_std / (n ** 0.5))
print('T test Value : {:.2f}'.format(t_test))


print('T value at {}% Significance : -2.08 to +2.08 for two tailed test'.format(alpha))

print('-' * 50)

print('-2.08 < -2.07. H0 is not rejected.')
print('Conclusion : Average family spends on Dental is $1135')
print('-' * 50)

--------------------------------------------------
Null Hypothesis :  Avg Family spends on Dental = 1135
Alternate Hypothesis :  Avg Family spends on Dental != 1135
--------------------------------------------------
T test Value : -2.07
T value at 0.05% Significance : -2.08 to +2.08 for two tailed test
--------------------------------------------------
-2.08 < -2.07. H0 is not rejected.
Conclusion : Average family spends on Dental is $1135
--------------------------------------------------


# Problem Statement 5:

## Solution

In [4]:
%reset -f

import numpy as np
from scipy import stats

h0 = 'Avg Annual Salary == $48,574'
h1 = 'Avg Annual Salary != $48,574'

print('-' * 50)

print('Null Hypothesis : ', h0)
print('Alternate Hypothesis : ', h1)

pop_mean = 48432

alpha = 0.05

n = 400
sample_mean = 48574
sample_std = 2000

print('-' * 50)

z_test = (sample_mean - pop_mean) / (sample_std / (n ** 0.5))
print('Z test Value : {:.2f}'.format(z_test))

z = np.abs(stats.norm.ppf(alpha))
print('Z value at {}% Significance : -1.96 to +1.96'.format(alpha, z))

print('-' * 50)

print('Since -1.96 < 1.42 < +1.96. Hence H0 cannot be rejected.')
print('Conclusion : Avg Salary is $48,574 at 5% level of significance.')
print('-' * 50)

--------------------------------------------------
Null Hypothesis :  Avg Annual Salary == $48,574
Alternate Hypothesis :  Avg Annual Salary != $48,574
--------------------------------------------------
Z test Value : 1.42
Z value at 0.05% Significance : -1.96 to +1.96
--------------------------------------------------
Since -1.96 < 1.42 < +1.96. Hence H0 cannot be rejected.
Conclusion : Avg Salary is $48,574 at 5% level of significance.
--------------------------------------------------


# Problem Statement 6:

## Solution

In [5]:
%reset -f

import numpy as np
from scipy import stats

h0 = 'Average price per square foot for warehouses in USA == $32.28'
h1 = 'Average price per square foot for warehouses in USA != $32.28'

print('-' * 50)

print('Null Hypothesis : ', h0)
print('Alternate Hypothesis : ', h1)

pop_mean = 32.28

alpha = 0.05

n = 19
df = n-1
sample_mean = 31.67
sample_std = 1.29

print('-' * 50)

t_test = (sample_mean - pop_mean) / (sample_std / (n ** 0.5))
print('T test Value : {:.2f}'.format(t_test))

print('T value at {} Significance is -2.101 to +2.101'.format(alpha))

print('-' * 50)

print('Since -2.101 < -2.06 < +2.101. H0 cannot be rejected.')
print('Conclusion : Average price per square foot for warehouses in USA is $32.28 at 5% level of significance.')
print('-' * 50)

--------------------------------------------------
Null Hypothesis :  Average price per square foot for warehouses in USA == $32.28
Alternate Hypothesis :  Average price per square foot for warehouses in USA != $32.28
--------------------------------------------------
T test Value : -2.06
T value at 0.05 Significance is -2.101 to +2.101
--------------------------------------------------
Since -2.101 < -2.06 < +2.101. H0 cannot be rejected.
Conclusion : Average price per square foot for warehouses in USA is $32.28 at 5% level of significance.
--------------------------------------------------


# Problem Statement 7:

<p> Fill in the blank spaces in the table and draw your conclusions from it. </p>
<html>
<table>
<tbody>
<tr>
<td>Acceptance Region</td>
<td>Sample Size</td>
<td>$\alpha$&nbsp;</td>
<td>$\beta$ at&nbsp;$\mu$ = 52</td>
<td>&nbsp;$\beta$ at&nbsp;$\mu$ = 50.5</td>
</tr>
<tr>
<td>&nbsp;48.5 &lt; $\bar{x}$ &lt; 51.5</td>
<td>&nbsp;10</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td>&nbsp;48 &lt; $\bar{x}$ &lt; 52</td>
<td>&nbsp;10</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td>&nbsp;48.81 &lt; $\bar{x}$ &lt; 51.9</td>
<td>&nbsp;16</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr>
<td>&nbsp;48.42 &lt; $\bar{x}$ &lt; 51.58</td>
<td>&nbsp;16</td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p>&nbsp;</p>
</html>

## Solution

In [6]:
%reset -f

import numpy as np
from scipy import stats

# Assumptions
# Population Mean = 50, Standard Deviation = 2.5


def get_z1_z2(lower, upper, pop_mean, sample_std):
    z1 = (lower - pop_mean) / sample_std
    z2 = (upper - pop_mean) / sample_std
    
    return z1, z2

def get_alpha_beta(lower, upper, sample_size, pop_mean = 50, pop_std_dev = 2.5):

    sample_std  = pop_std_dev / (sample_size ** 0.5)
    z1, z2 = get_z1_z2(lower, upper, pop_mean, sample_std)

    # Calculating value of alpha

    alpha = np.abs(stats.norm.cdf(z1)) + 1 - np.abs(stats.norm.cdf(z2))

    # Calculating value of beta at 52

    pop_mean = 52
    z1, z2 = get_z1_z2(lower, upper, pop_mean, sample_std)
    beta1 = np.abs(stats.norm.cdf(z2)) - np.abs(stats.norm.cdf(z1))
    
    # Calculating value of beta at 50.5

    pop_mean = 50.5
    z1, z2 = get_z1_z2(lower, upper, pop_mean, sample_std)
    beta2 = np.abs(stats.norm.cdf(z2)) - np.abs(stats.norm.cdf(z1))

    return alpha, beta1, beta2


def display(alpha, beta1, beta2, lower, upper):
    print('-' * 50)
    print('Acceptance Region : {} < x < {}'.format(lower, upper))
    print('-' * 50)
    
    print('Alpha : {:.2f}'.format(alpha))
    print('Beta at u = 52 : {:.2f}'.format(beta1))
    print('Beta at u = 50.5 : {:.2f}'.format(beta2))
    
    

# For Acceptance Region : 48.5 < x < 51.5


alpha, beta1, beta2 = get_alpha_beta(lower = 48.5, upper = 51.5, sample_size = 10)
display(alpha, beta1, beta2, lower = 48.5, upper = 51.5)


# For Acceptance Region : 48 < x < 52

alpha, beta1, beta2 = get_alpha_beta(lower = 48, upper = 52, sample_size = 10)
display(alpha, beta1, beta2, lower = 48, upper = 52)


# For Acceptance Region : 48.81 < x < 51.19

alpha, beta1, beta2 = get_alpha_beta(lower = 48.81, upper = 51.19, sample_size = 16)
display(alpha, beta1, beta2, lower = 48.81, upper = 51.19)


# For Acceptance Region : 48.42 < x < 51.58

alpha, beta1, beta2 = get_alpha_beta(lower = 48.42, upper = 51.58, sample_size = 16)
display(alpha, beta1, beta2, lower = 48.42, upper = 51.58)

--------------------------------------------------
Acceptance Region : 48.5 < x < 51.5
--------------------------------------------------
Alpha : 0.06
Beta at u = 52 : 0.26
Beta at u = 50.5 : 0.89
--------------------------------------------------
Acceptance Region : 48 < x < 52
--------------------------------------------------
Alpha : 0.01
Beta at u = 52 : 0.50
Beta at u = 50.5 : 0.97
--------------------------------------------------
Acceptance Region : 48.81 < x < 51.19
--------------------------------------------------
Alpha : 0.06
Beta at u = 52 : 0.10
Beta at u = 50.5 : 0.86
--------------------------------------------------
Acceptance Region : 48.42 < x < 51.58
--------------------------------------------------
Alpha : 0.01
Beta at u = 52 : 0.25
Beta at u = 50.5 : 0.96


### The below table summarizes the data

<html>
<table>
<tbody>
<tr>
<td>Acceptance Region</td>
<td>Sample Size</td>
<td>$\alpha$&nbsp;</td>
<td>$\beta$ at&nbsp;$\mu$ = 52</td>
<td>&nbsp;$\beta$ at&nbsp;$\mu$ = 50.5</td>
</tr>
<tr>
<td>&nbsp;48.5 &lt; $\bar{x}$ &lt; 51.5</td>
<td>&nbsp;10</td>
<td>&nbsp;0.06</td>
<td>&nbsp;0.26</td>
<td>&nbsp;0.89</td>
</tr>
<tr>
<td>&nbsp;48 &lt; $\bar{x}$ &lt; 52</td>
<td>&nbsp;10</td>
<td>&nbsp;0.01</td>
<td>&nbsp;0.50</td>
<td>&nbsp;0.97</td>
</tr>
<tr>
<td>&nbsp;48.81 &lt; $\bar{x}$ &lt; 51.9</td>
<td>&nbsp;16</td>
<td>&nbsp;0.06</td>
<td>&nbsp;0.10</td>
<td>&nbsp;0.86</td>
</tr>
<tr>
<td>&nbsp;48.42 &lt; $\bar{x}$ &lt; 51.58</td>
<td>&nbsp;16</td>
<td>&nbsp;0.01</td>
<td>&nbsp;0.25</td>
<td>&nbsp;0.96</td>
</tr>
</tbody>
</table>
<p>&nbsp;</p>
</html>

# Problem Statement 8:

## Solution

In [7]:
%reset -f

u = 10

n = 16
x = 12
s = 1.5

t = (x - u) / (s / (n ** 0.5))
print('T Score : {:.2f}'.format(t))

T Score : 5.33


# Problem Statement 9:

## Solution

In [8]:
%reset -f

import numpy as np
from scipy import stats

n = 16
df = n - 1
a = 0.01

t_score = np.abs(stats.t.ppf(a, df))
print('T score : {:.3f}'.format(t_score))

T score : 2.602


# Problem Statement 10:

## Solution

In [9]:
%reset -f

import numpy as np
from scipy import stats

n = 25
df = n - 1
x = 60
s = 4
a = 0.05
a_2 = a / 2

t1 = stats.t.ppf(a_2, df)
t2 = np.abs(stats.t.ppf(a_2, df))

print('T Score Range : {:.2f} to {:.2f}'.format(t1, t2))

# -t(0.05) = -1.711
# t(0.10) = +1.318

p_value = 1 - (0.05 + 0.10)
print('Probability : ', p_value)

T Score Range : -2.06 to 2.06
Probability :  0.85


# Problem Statement 11:

## Solution

In [10]:
%reset -f

import numpy as np
from scipy import stats

H0 = 'Population Travelling is different.'
H1 = 'Population Travelling is same.'

print('Two tailed test need to be conducted.')

n1 = 1200
x1 = 452
s1 = 212

n2 = 800
x2 = 523
s2 = 185


Assumption = 'Population is same hence mean is same'
alpha = 0.05
alpha_2 = 0.025

print('Z score acceptable range : -1.96 to +1.96')

z_score = (x1 - x2) / (((s1 ** 2) / n1) + ((s2 ** 2) / n2)) ** 0.5
print('Computed Z score : {:.2f}'.format(z_score))
print('Since -7.93 < -1.96, H0 is rejected.')

Two tailed test need to be conducted.
Z score acceptable range : -1.96 to +1.96
Computed Z score : -7.93
Since -7.93 < -1.96, H0 is rejected.


# Problem Statement 12:

## Solution

In [11]:
%reset -f

import numpy as np
from scipy import stats

H0 = 'People preferring Duracell battery is different from people preferring Energizer battery.'
H1 = 'People preferring Duracell battery is same from people preferring Energizer battery.'

print('Two tailed test need to be conducted.')

n1 = 100
x1 = 308
s1 = 84

n2 = 100
x2 = 254
s2 = 67


Assumption = 'Population is same hence mean is same'
alpha = 0.05
alpha_2 = 0.025

print('Z score acceptable range : -1.96 to +1.96')

z_score = (x1 - x2) / (((s1 ** 2) / n1) + ((s2 ** 2) / n2)) ** 0.5
print('Computed Z score : {:.2f}'.format(z_score))
print('Since -7.93 < -1.96, H0 is rejected.')

Two tailed test need to be conducted.
Z score acceptable range : -1.96 to +1.96
Computed Z score : 5.03
Since -7.93 < -1.96, H0 is rejected.


# Problem Statement 13:

## Solution

In [12]:
%reset -f

import numpy as np
from scipy import stats

H0 = 'Average price of sugar increases'
H1 = 'Avergae price of sugar doesnot increases'

print('Two tailed test need to be conducted.')

n1 = 14
x1 = 0.317
s1 = 0.12

n2 = 9
x2 = 0.21
s2 = 0.11

df = n1 + n2 - 2


Assumption = 'Population is same hence mean is same'
alpha = 0.05
alpha_2 = 0.025

print('T score acceptable range : -2.08 to +2.08')

t_score = (x1 - x2) / ((((n1 - 1) * s1**2 + (n2 - 1) * s2**2 ) / df) * (1 / n1 + 1 / n2)) ** 0.5

print('Computed T score : {:.2f}'.format(t_score))
print('Since {:.2f} > 2.08, H0 is rejected.'.format(t_score))

Two tailed test need to be conducted.
T score acceptable range : -2.08 to +2.08
Computed T score : 2.15
Since 2.15 > 2.08, H0 is rejected.


# Problem Statement 14:

## Solution

In [13]:
%reset -f

import numpy as np
from scipy import stats


H0 = 'Small price reduction increases sale'
H1 = 'Small price reduction doesnot increase sale'

print('Two tailed test need to be conducted.')

n1 = 15
x1 = 6598
s1 = 844

n2 = 12
x2 = 6870
s2 = 669

df = n1 + n2 - 2


Assumption = 'Population is same hence mean is same'
alpha = 0.05
alpha_2 = 0.025

print('T score acceptable range : -2.06 to +2.06')

t_score = (x1 - x2) / ((((n1 - 1) * s1**2 + (n2 - 1) * s2**2 ) / df) * (1 / n1 + 1 / n2)) ** 0.5

print('Computed T score : {:.2f}'.format(t_score))
print('Since -2.06 < {:.2f} < 1.96, H0 can\'t be rejected.'.format(t_score))

Two tailed test need to be conducted.
T score acceptable range : -2.06 to +2.06
Computed T score : -0.91
Since -2.06 < -0.91 < 1.96, H0 can't be rejected.


# Problem Statement 15:

## Solution

In [14]:
%reset -f

import numpy as np
from scipy import stats

H0 = 'Populations are same'
H1 = 'Populations are different'

print('Two tailed test need to be conducted.')

n1 = 1000
x1 = 53
p1 = 0.53

n2 = 100
x2 = 43
p2 = 0.53

p = (p1 + p2) / 2


Assumption = 'Population is same hence mean is same'
alpha = 0.05
alpha_2 = 0.025

print('Z score acceptable range : -1.96 to +1.96')

z_score = (p1 - p2) / (((p * (1 - p)) / n1) + ((p * (1 - p)) / n2)) ** 0.5

print('Computed Z score : {:.2f}'.format(z_score))
print('Since -1.96 < {:.2f} < 1.96, H0 can\'t be rejected.'.format(z_score))

Two tailed test need to be conducted.
Z score acceptable range : -1.96 to +1.96
Computed Z score : 0.00
Since -1.96 < 0.00 < 1.96, H0 can't be rejected.


# Problem Statement 16:

## Solution

In [15]:
%reset -f

import numpy as np
from scipy import stats

H0 = 'Travellers check buyers when sweepstakes prices are offered atleast 10% Higher.'
H1 = 'Travellers check buyers when no sweepstakes on.'

print('One tailed test need to be conducted.')

n1 = 300
x1 = 120
p1 = 0.40

n2 = 700
x2 = 140
p2 = 0.20

p = (p1 + p2) / 2

alpha = 0.05

print('Z score acceptable range : x > -1.64.')

z_score = (p1 - p2) / (((p * (1 - p)) / n1) + ((p * (1 - p)) / n2)) ** 0.5

print('Computed Z score : {:.2f}.'.format(z_score))
print('Since {:.2f} > 1.96, H0 can\'t be rejected.'.format(z_score))

One tailed test need to be conducted.
Z score acceptable range : x > -1.64.
Computed Z score : 6.32.
Since 6.32 > 1.96, H0 can't be rejected.


# Problem Statement 17: 

## Solution

In [16]:
%reset -f

H0 = 'It is biased die.'
H1 = 'It is not a biased die.'

list1 = [16, 20, 25, 14, 29, 28]
list2 = [22, 22, 22, 22, 22, 22]
s = 0
for i in range(len(list2)):
    s += (((list1[i] - list2[i]) ** 2)) / list2[i]
    

df = (6 - 1)
alpha = 0.05
table_value = 11.07

print('-' * 50)
print('Null Hypothesis : ', H0)
print('Alternate Hypothesis : ', H1)
print('-' * 50)
print('Original Value')
print('-' * 50)
print(list1)
print('-' * 50)
print('Expected Value')
print('-' * 50)
print(list2)
print('-' * 50)
print('Degree of Freedom : ', df)
print('Alpha Value : ', alpha)
print('Chi-squared value from table is : {}'.format(table_value))
print('-' * 50)

print('Computed Chi-squared value is : {:.2f}'.format(s))   
print('Since {:.2f} < {}. H0 is not rejected.'.format(s, table_value))
print('-' * 50)
print('Conclusion : It is a biased die.')
print('-' * 50)

--------------------------------------------------
Null Hypothesis :  It is biased die.
Alternate Hypothesis :  It is not a biased die.
--------------------------------------------------
Original Value
--------------------------------------------------
[16, 20, 25, 14, 29, 28]
--------------------------------------------------
Expected Value
--------------------------------------------------
[22, 22, 22, 22, 22, 22]
--------------------------------------------------
Degree of Freedom :  5
Alpha Value :  0.05
Chi-squared value from table is : 11.07
--------------------------------------------------
Computed Chi-squared value is : 9.00
Since 9.00 < 11.07. H0 is not rejected.
--------------------------------------------------
Conclusion : It is a biased die.
--------------------------------------------------


# Problem Statement 18:

<p>In a certain town, there are about one million eligible voters. A simple random 
sample of 10,000 eligible voters was chosen to study the relationship between 
gender and participation in the last election. The results are summarized in the 
following 2X2 (read two by two) contingency table: </p>

<table>
<tbody>
<tr>
<td>&nbsp;</td>
<td>&nbsp;Men</td>
<td>Women</td>
</tr>
<tr>
<td>&nbsp;Voted</td>
<td>2792</td>
<td>3591</td>
</tr>
<tr>
<td>Not Voted</td>
<td>1486</td>
<td>2131</td>
</tr>
</tbody>
</table>

<p>We would want to check whether being a man or a woman (columns) is independent of 
having voted in the last election (rows). In other words, is “gender and voting independent”?</p>

## Solution

In [17]:
%reset -f

import numpy as np

list1 = [[2792, 3591], [1486, 2131]]
list1 = np.array(list1)

list2 = []
for i in np.sum(list1, axis=1):
    for j in np.sum(list1, axis=0):
        list2.append(np.round((i * j) / np.sum(list1), 2))

list2 = np.array(list2)
s = 0

for i in range(len(list2)):
    s += (((list1.ravel()[i] - list2[i]) ** 2)) / list2[i]
    
    
H0 = 'Gender and Voting are Independent'
H1 = 'Gender and Voting are not Independent'    
  
df = (2 - 1) * (2 - 1) 
alpha = 0.05
table_value = 21.03

print('-' * 50)
print('Null Hypothesis : ', H0)
print('Alternate Hypothesis : ', H1)
print('-' * 50)
print('Original Value')
print('-' * 50)
print(list1)
print('-' * 50)
print('Expected Value')
print('-' * 50)
print(list2)
print('-' * 50)
print('Degree of Freedom : ', df)
print('Alpha Value : ', alpha)
print('Chi-squared value from table is : {}'.format(table_value))
print('-' * 50)

print('Computed Chi-squared value is : {:.2f}'.format(s))   
print('Since {:.2f} < {}. H0 is not rejected.'.format(s, table_value))
print('-' * 50)
print('Conclusion : Gender and Voting are Independent')
print('-' * 50)

--------------------------------------------------
Null Hypothesis :  Gender and Voting are Independent
Alternate Hypothesis :  Gender and Voting are not Independent
--------------------------------------------------
Original Value
--------------------------------------------------
[[2792 3591]
 [1486 2131]]
--------------------------------------------------
Expected Value
--------------------------------------------------
[2730.65 3652.35 1547.35 2069.65]
--------------------------------------------------
Degree of Freedom :  1
Alpha Value :  0.05
Chi-squared value from table is : 21.03
--------------------------------------------------
Computed Chi-squared value is : 6.66
Since 6.66 < 21.03. H0 is not rejected.
--------------------------------------------------
Conclusion : Gender and Voting are Independent
--------------------------------------------------


# Problem Statement 19:

<p>A sample of 100 voters are asked which of four candidates they would vote for in an 
election. The number supporting each candidate is given below:
</p>


<table>
<tbody>
<tr>
<td>&nbsp;Higgins</td>
<td>Reardon</td>
<td>White</td>
<td>Charlton</td>
</tr>
<tr>
<td>&nbsp;41</td>
<td>19</td>
<td>24</td>
<td>16</td>
</tr>
</tbody>
</table>


## Solution

In [18]:
%reset -f

H0 = 'Candidates are equally popular'
H1 = 'Candidates are not equally popular'


list1 = [41, 19, 24, 16]
list2 = [25, 25, 25, 25]
s = 0
for i in range(len(list2)):
    s += (((list1[i] - list2[i]) ** 2)) / list2[i]
    

df = (4 - 1) 
alpha = 0.05
table_value = 7.81


print('-' * 50)
print('Null Hypothesis : ', H0)
print('Alternate Hypothesis : ', H1)
print('-' * 50)
print('Original Value')
print('-' * 50)
print(list1)
print('-' * 50)
print('Expected Value')
print('-' * 50)
print(list2)
print('-' * 50)
print('Degree of Freedom : ', df)
print('Alpha Value : ', alpha)
print('Chi-squared value from table is : {}'.format(table_value))
print('-' * 50)

print('Computed Chi-squared value is : {:.2f}'.format(s))   
print('Since {:.2f} > {}. H0 is rejected.'.format(s, table_value))
print('-' * 50)
print('Conclusion : The candidates are not equally popular.')
print('-' * 50)

--------------------------------------------------
Null Hypothesis :  Candidates are equally popular
Alternate Hypothesis :  Candidates are not equally popular
--------------------------------------------------
Original Value
--------------------------------------------------
[41, 19, 24, 16]
--------------------------------------------------
Expected Value
--------------------------------------------------
[25, 25, 25, 25]
--------------------------------------------------
Degree of Freedom :  3
Alpha Value :  0.05
Chi-squared value from table is : 7.81
--------------------------------------------------
Computed Chi-squared value is : 14.96
Since 14.96 > 7.81. H0 is rejected.
--------------------------------------------------
Conclusion : The candidates are not equally popular.
--------------------------------------------------


# Problem Statement 20:

Children of three ages are asked to indicate their preference for three photographs of 
adults. Do the data suggest that there is a significant relationship between age and 
photograph preference? What is wrong with this study? [Chi-Square = 29.6, with 4 
df: 𝑝 < 0.05].

## Solution:

In [19]:
%reset -f

import numpy as np

list1 = [[18, 22, 20], [2, 28, 40], [20, 10, 40]]
list1 = np.array(list1)

list2 = []
for i in np.sum(list1, axis=1):
    for j in np.sum(list1, axis=0):
        list2.append(np.round((i * j) / np.sum(list1), 2))

list2 = np.array(list2)
s = 0

for i in range(len(list2)):
    s += (((list1.ravel()[i] - list2[i]) ** 2)) / list2[i]
    
    
df = (3 - 1) * (3 - 1)
alpha = 0.05
table_value = 9.49

H0 = 'There is no relationship.'
H1 = 'There is a relationship.'

print('-' * 50)
print('Null Hypothesis : ', H0)
print('Alternate Hypothesis : ', H1)
print('-' * 50)
print('Original Value')
print('-' * 50)
print(list1)
print('-' * 50)
print('Expected Value')
print('-' * 50)
print(np.reshape(list2, (3, 3)))
print('-' * 50)
print('Degree of Freedom : ', df)
print('Alpha Value : ', alpha)
print('Chi-squared value from table is : {}'.format(table_value))
print('-' * 50)

print('Computed Chi-squared value is : {:.2f}'.format(s))   
print('Since {:.2f} > {}. H0 is rejected.'.format(s, table_value))
print('-' * 50)
print('Conclusion : There is a significant relationship between age and photograph preference')
print('-' * 50)

--------------------------------------------------
Null Hypothesis :  There is no relationship.
Alternate Hypothesis :  There is a relationship.
--------------------------------------------------
Original Value
--------------------------------------------------
[[18 22 20]
 [ 2 28 40]
 [20 10 40]]
--------------------------------------------------
Expected Value
--------------------------------------------------
[[12. 18. 30.]
 [14. 21. 35.]
 [14. 21. 35.]]
--------------------------------------------------
Degree of Freedom :  4
Alpha Value :  0.05
Chi-squared value from table is : 9.49
--------------------------------------------------
Computed Chi-squared value is : 29.60
Since 29.60 > 9.49. H0 is rejected.
--------------------------------------------------
Conclusion : There is a significant relationship between age and photograph preference
--------------------------------------------------


# Problem Statement 21: 

<p>A study of conformity using the Asch paradigm involved two conditions: one where 
one confederate supported the true judgement and another where no confederate 
gave the correct response.</p>

<table>
<tbody>
<tr>
<td>&nbsp;</td>
<td>&nbsp;Support</td>
<td>No Support</td>
</tr>
<tr>
<td>&nbsp;Conform</td>
<td>18</td>
<td>40</td>
</tr>
<tr>
<td>Not Conform</td>
<td>32</td>
<td>10</td>
</tr>
</tbody>
</table>

<p>Is there a significant difference between the "support" and "no support" conditions in the 
frequency with which individuals are likely to conform? [Chi-Square = 19.87, with 1 df:
𝑝 < 0.05].</p>

## Solution

In [20]:
%reset -f

import numpy as np

list1 = [[18, 40], [32, 10]]
list1 = np.array(list1)

list2 = []
for i in np.sum(list1, axis=1):
    for j in np.sum(list1, axis=0):
        list2.append(np.round((i * j) / np.sum(list1), 2))

list2 = np.array(list2)
s = 0

for i in range(len(list2)):
    s += (((list1.ravel()[i] - list2[i]) ** 2)) / list2[i]

    
df = (2 - 1) * (2 - 1)
alpha = 0.05
table_value = 3.84 

H0 = 'There is no relationship.'
H1 = 'There is a relationship.'

print('-' * 50)
print('Null Hypothesis : ', H0)
print('Alternate Hypothesis : ', H1)
print('-' * 50)
print('Original Value')
print('-' * 50)
print(list1)
print('-' * 50)
print('Expected Value')
print('-' * 50)
print(np.reshape(list2, (2, 2)))
print('-' * 50)
print('Degree of Freedom : ', df)
print('Alpha Value : ', alpha)
print('Chi-squared value from table is : {}'.format(table_value))
print('-' * 50)

print('Computed Chi-squared value is : {:.2f}'.format(s))   
print('Since {:.2f} > {}. H0 is rejected.'.format(s, table_value))
print('-' * 50)
print('Conclusion : There is a significant difference between the "support" and "no support" conditions in the  frequency with which individuals are likely to conform')
print('-' * 50)

--------------------------------------------------
Null Hypothesis :  There is no relationship.
Alternate Hypothesis :  There is a relationship.
--------------------------------------------------
Original Value
--------------------------------------------------
[[18 40]
 [32 10]]
--------------------------------------------------
Expected Value
--------------------------------------------------
[[29. 29.]
 [21. 21.]]
--------------------------------------------------
Degree of Freedom :  1
Alpha Value :  0.05
Chi-squared value from table is : 3.84
--------------------------------------------------
Computed Chi-squared value is : 19.87
Since 19.87 > 3.84. H0 is rejected.
--------------------------------------------------
Conclusion : There is a significant difference between the "support" and "no support" conditions in the  frequency with which individuals are likely to conform
--------------------------------------------------


# Problem Statement 22:

We want to test whether short people differ with respect to their leadership qualities 
(Genghis Khan, Adolf Hitler and Napoleon were all stature-deprived, and how many midget 
MP's are there?) The following table shows the frequencies with which 43 short people and 
52 tall people were categorized as "leaders", "followers" or as "unclassifiable". Is there a 
relationship between height and leadership qualities? 
[Chi-Square = 10.71, with 2 df: 𝑝 < 0.01].


## Solution

In [21]:
%reset -f

import numpy as np

list1 = [[12, 32], [22, 14], [9, 6]]
list1 = np.array(list1)

list2 = []
for i in np.sum(list1, axis=1):
    for j in np.sum(list1, axis=0):
        list2.append(np.round((i * j) / np.sum(list1), 2))

list2 = np.array(list2)
s = 0

for i in range(len(list2)):
    s += (((list1.ravel()[i] - list2[i]) ** 2)) / list2[i]


df = (3 - 1) * (2 - 1)
alpha = 0.05
table_value = 9.21

H0 = 'There is no relationship.'
H1 = 'There is a relationship.'

print('-' * 50)
print('Null Hypothesis : ', H0)
print('Alternate Hypothesis : ', H1)
print('-' * 50)
print('Original Value')
print('-' * 50)
print(list1)
print('-' * 50)
print('Expected Value')
print('-' * 50)
print(np.reshape(list2, (3, 2)))
print('-' * 50)
print('Degree of Freedom : ', df)
print('Alpha Value : ', alpha)
print('Chi-squared value from table is : {}'.format(table_value))
print('-' * 50)

print('Computed Chi-squared value is : {:.2f}'.format(s))   
print('Since {:.2f} > {}. H0 is rejected.'.format(s, table_value))
print('-' * 50)
print('Conclusion : There is a relation between height and leadership.')
print('-' * 50)

--------------------------------------------------
Null Hypothesis :  There is no relationship.
Alternate Hypothesis :  There is a relationship.
--------------------------------------------------
Original Value
--------------------------------------------------
[[12 32]
 [22 14]
 [ 9  6]]
--------------------------------------------------
Expected Value
--------------------------------------------------
[[19.92 24.08]
 [16.29 19.71]
 [ 6.79  8.21]]
--------------------------------------------------
Degree of Freedom :  2
Alpha Value :  0.05
Chi-squared value from table is : 9.21
--------------------------------------------------
Computed Chi-squared value is : 10.72
Since 10.72 > 9.21. H0 is rejected.
--------------------------------------------------
Conclusion : There is a relation between height and leadership.
--------------------------------------------------


# Problem Statement 23: 

Each respondent in the Current Population Survey of March 1993 was classified as 
employed, unemployed, or outside the labor force. The results for men in California age 35-
44 can be cross-tabulated by marital status, as follows:

Men of different marital status seem to have different distributions of labor force status. Or is 
this just chance variation? (you may assume the table results from a simple random 
sample.)


## Solution

In [22]:
%reset -f

import numpy as np

list1 = [[679, 103, 114], [63, 10, 20], [42, 18, 25]]
list1 = np.array(list1)

list2 = []
for i in np.sum(list1, axis=1):
    for j in np.sum(list1, axis=0):
        list2.append(np.round((i * j) / np.sum(list1), 2))

list2 = np.array(list2)
s = 0

for i in range(len(list2)):
    s += (((list1.ravel()[i] - list2[i]) ** 2)) / list2[i]

df = (3 - 1) * (3 - 1)
alpha = 0.05
table_value = 9.49

H0 = 'There is no relationship.'
H1 = 'There is a relationship.'

print('-' * 50)
print('Null Hypothesis : ', H0)
print('Alternate Hypothesis : ', H1)
print('-' * 50)
print('Original Value')
print('-' * 50)
print(list1)
print('-' * 50)
print('Expected Value')
print('-' * 50)
print(np.reshape(list2, (3, 3)))
print('-' * 50)
print('Degree of Freedom : ', df)
print('Alpha Value : ', alpha)
print('Chi-squared value from table is : {}'.format(table_value))
print('-' * 50)

print('Computed Chi-squared value is : {:.2f}'.format(s))   
print('Since {:.2f} > {}. H0 is rejected.'.format(s, table_value))
print('-' * 50)
print('Conclusion : Maritial status and Employment are related.')
print('-' * 50)

--------------------------------------------------
Null Hypothesis :  There is no relationship.
Alternate Hypothesis :  There is a relationship.
--------------------------------------------------
Original Value
--------------------------------------------------
[[679 103 114]
 [ 63  10  20]
 [ 42  18  25]]
--------------------------------------------------
Expected Value
--------------------------------------------------
[[654.06 109.29 132.65]
 [ 67.89  11.34  13.77]
 [ 62.05  10.37  12.58]]
--------------------------------------------------
Degree of Freedom :  4
Alpha Value :  0.05
Chi-squared value from table is : 9.49
--------------------------------------------------
Computed Chi-squared value is : 31.62
Since 31.62 > 9.49. H0 is rejected.
--------------------------------------------------
Conclusion : Maritial status and Employment are related.
--------------------------------------------------
