In [1]:
import numpy as np

<h3>Write a function so that the columns of the output matrix are powers of the input
vector. <br><br>
The order of the powers is determined by the increasing boolean argument. Specifically, when<br>
increasing is False, the i-th output column is the input vector raised element-wise to the power<br>
of N - i - 1.<br><br>
HINT: Such a matrix with a geometric progression in each row is named for Alexandre-<br>
Theophile Vandermonde.</h3>

In [2]:
def func(N, mat, vec, increasing):
    
    if increasing == False:
        for i in range(N):
            mat[:,i] = vec ** (N - i - 1)
    else:
        for i in range(N):
            mat[:,i] = vec ** i
            
    return mat


n = 4

matrix = np.array(np.ones((n, n)))
vector = np.array(np.random.randint(1, 4, n))

print('Generated Vector : \n', vector.reshape(-1, 1))
print('-------------------')

print('Increasing set to False : \n', func(n, matrix, vector, False))
print('Increasing set to True : \n', func(n, matrix, vector, True))

Generated Vector : 
 [[2]
 [2]
 [3]
 [2]]
-------------------
Increasing set to False : 
 [[ 8.  4.  2.  1.]
 [ 8.  4.  2.  1.]
 [27.  9.  3.  1.]
 [ 8.  4.  2.  1.]]
Increasing set to True : 
 [[ 1.  2.  4.  8.]
 [ 1.  2.  4.  8.]
 [ 1.  3.  9. 27.]
 [ 1.  2.  4.  8.]]


<h3> Write a function to find moving average in an array over a window:<br>
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.</h3>

In [3]:
def func(arr, win):
    sum_list = np.array([])
    
    for i in range(len(arr) - win + 1):
        summ = 0
        
        for j in range(i, i + win):
            summ += arr[j]
            
        sum_list = np.append(sum_list, summ / win)

    return np.around(sum_list, decimals = 2)

array = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
window = 3

moving_avg = func(array, window)

print('Moving average : ', moving_avg)
print('Length of moving average values : ', len(moving_avg))

Moving average :  [  5.     4.67   5.67   6.67   9.67  28.67  49.33  72.67  84.    93.33
 116.33]
Length of moving average values :  11
