# Problem Statement 1:

## Solution

In [1]:
%reset -f

import numpy as np

list1 = [[54, 46, 41, 201], [44, 53, 57, 194], [98, 99, 98, 395]]
list1 = np.array(list1)

list2 = []
for i in np.sum(list1, axis=1):
    for j in np.sum(list1, axis=0):
        list2.append(np.round((i * j) / np.sum(list1), 2))

list2 = np.array(list2)
s = 0

for i in range(len(list2)):
    s += (((list1.ravel()[i] - list2[i]) ** 2)) / list2[i]

df = (3 - 1) * (4 - 1)
alpha = 0.05
table_value = 9.49

H0 = 'Gender is independent of Education Level.'
H1 = 'Gender is not independent of Education Level.'

print('-' * 50)
print('Null Hypothesis : ', H0)
print('Alternate Hypothesis : ', H1)
print('-' * 50)
print('Original Value')
print('-' * 50)
print(list1)
print('-' * 50)
print('Expected Value')
print('-' * 50)
print(np.reshape(list2, (3, 4)))
print('-' * 50)
print('Degree of Freedom : ', df)
print('Alpha Value : ', alpha)
print('Chi-squared value from table is : {}'.format(table_value))
print('-' * 50)

print('Computed Chi-squared value is : {:.2f}'.format(s))   
print('Since {:.2f} < {}. H0 cant be rejected.'.format(s, table_value))
print('-' * 50)
print('Conclusion : Gender is independent of Education Level.')
print('-' * 50)

--------------------------------------------------
Null Hypothesis :  Gender is independent of Education Level.
Alternate Hypothesis :  Gender is not independent of Education Level.
--------------------------------------------------
Original Value
--------------------------------------------------
[[ 54  46  41 201]
 [ 44  53  57 194]
 [ 98  99  98 395]]
--------------------------------------------------
Expected Value
--------------------------------------------------
[[ 48.57  49.07  48.57 195.78]
 [ 49.43  49.93  49.43 199.22]
 [ 98.    99.    98.   395.  ]]
--------------------------------------------------
Degree of Freedom :  6
Alpha Value :  0.05
Chi-squared value from table is : 9.49
--------------------------------------------------
Computed Chi-squared value is : 4.20
Since 4.20 < 9.49. H0 cant be rejected.
--------------------------------------------------
Conclusion : Gender is independent of Education Level.
--------------------------------------------------


# Problem Statement 2:

## Solution

In [2]:
%reset -f

import numpy as np

list1 = np.array([51, 45, 33, 45, 67])
list2 = np.array([23, 43, 23, 43, 45])
list3 = np.array([56, 76, 74, 87, 56])

# list1 = np.array([2, 4, 6])
# list2 = np.array([3, 5, 7])
# list3 = np.array([4, 6, 8])


mean_list1 = list1.mean()
mean_list2 = list2.mean()
mean_list3 = list3.mean()

print('-' * 50)
print('Mean of list1 : ', mean_list1)
print('Mean of list2 : ', mean_list2)
print('Mean of list3 : ', mean_list3)
print('-' * 50)

grand_mean = (mean_list1 + mean_list2 + mean_list3) / 3
print('Grand Mean : {:.2f}'.format(grand_mean))
print('-' * 50)

sum1 = 0
sum2 = 0
sum3 = 0



sum1 = ((mean_list1 - grand_mean) ** 2) * 5
sum2 = ((mean_list2 - grand_mean) ** 2) * 5
sum3 = ((mean_list3 - grand_mean) ** 2) * 5

ssc = sum1 + sum2 + sum3
print('Sum of Squares between the samples (SSC) : {:.2f}'.format(ssc))

sse = 0

for i in range(list1.shape[0]):
    sse += ((list1[i] - mean_list1) ** 2) + ((list2[i] - mean_list2) ** 2) + ((list3[i] - mean_list3 ) ** 2)
    
    
print('Sum of Squares within the samples (SSE) : {:.2f}'.format(sse))  

print('Total (SSC + SSE) : {:.2f}'.format(ssc + sse)) 
print('-' * 50)

print('Degree of freedom in the Numerator : {}'.format(3 - 1))
print('Degree of freedom in the Denominator : {}'.format(15 - 3))
print('Total : {}'.format(3 - 1 + 15 - 3)) 
print('-' * 50)

msc = ssc / (3 - 1)
mse = sse / (15 - 3)

print('Mean sum of Squares between the samples (MSC) : {:.2f}'.format(msc))
print('Mean sum of Squares within the samples (MSE) : {:.2f}'.format(mse))
print('Total (MSC + MSE) : {:.2f}'.format(msc + mse)) 
print('-' * 50)

f = msc / mse
print('Computed F-Stat Value : {:.2f}'.format(f))
print('F Value from Table (alpha = 0.05) : {:.2f}'.format(3.885))
print('-' * 50)

print('Since {:.2f} > {:.2f}. H0 is rejected.'.format(f, 3.885))


--------------------------------------------------
Mean of list1 :  48.2
Mean of list2 :  35.4
Mean of list3 :  69.8
--------------------------------------------------
Grand Mean : 51.13
--------------------------------------------------
Sum of Squares between the samples (SSC) : 3022.93
Sum of Squares within the samples (SSE) : 1860.80
Total (SSC + SSE) : 4883.73
--------------------------------------------------
Degree of freedom in the Numerator : 2
Degree of freedom in the Denominator : 12
Total : 14
--------------------------------------------------
Mean sum of Squares between the samples (MSC) : 1511.47
Mean sum of Squares within the samples (MSE) : 155.07
Total (MSC + MSE) : 1666.53
--------------------------------------------------
Computed F-Stat Value : 9.75
F Value from Table (alpha = 0.05) : 3.88
--------------------------------------------------
Since 9.75 > 3.88. H0 is rejected.


# Problem Statement 3:

Calculate F Test for given 10, 20, 30, 40, 50 and 5,10,15, 20, 25.
For 10, 20, 30, 40, 50:

## Solution

In [3]:
%reset -f

import numpy as np 

list1 = np.array([10, 20, 30, 40, 50])
list2 = np.array([5, 10, 15, 20, 25])

list1_mean = list1.mean()
list2_mean = list2.mean()

var1 = 0
var2 = 0

for i in range(len(list1)):
    var1 += ((list1[i] - list1_mean) ** 2) / (len(list1) - 1)
    var2 += ((list2[i] - list2_mean) ** 2) / (len(list2) - 1)
    

print('Computer Variance for 1st Distribution : ', var1)
print('Computer Variance for 2nd Distribution : ', var2)

print('F-Test Value : {}'.format(max(var1, var2) / min(var1, var2)))

Computer Variance for 1st Distribution :  250.0
Computer Variance for 2nd Distribution :  62.5
F-Test Value : 4.0
